### ISSUE TITLE
可以指定默认子应用启动吗

### ISSUE THREAD

**Issue by sxhieen** [worktile/ngx-planet#108]
打开时默认重定向到指定子应用，子应用display: none，没有显示出来

**Comment by why520crazy** [comment]
> 打开时默认重定向到指定子应用，子应用display: none，没有显示出来

你是怎么重定向的，只要路由匹配到子应用的路由就会展示的

**Comment by why520crazy** [comment]
初始化在Portal中路由跳转到子应用路由即可。

**Comment by sxhieen** [comment]
> > 打开时默认重定向到指定子应用，子应用display: none，没有显示出来
> 
> 你是怎么重定向的，只要路由匹配到子应用的路由就会展示的

path: '',
redirectTo: 'xxx',
pathMatch: 'full'

我是在app-routing.module里这样设置的

**Comment by why520crazy** [comment]
那你看看xxx是不是子应用的路由，有没有匹配到子应用

**Comment by sxhieen** [comment]
> 那你看看xxx是不是子应用的路由，有没有匹配到子应用

应该是有匹配到的，因为一刷新就显示出来了，只是首次打开重定向的话，就display: none，dom都在

**Comment by why520crazy** [comment]
> > 那你看看xxx是不是子应用的路由，有没有匹配到子应用
> 
> 应该是有匹配到的，因为一刷新就显示出来了，只是首次打开重定向的话，就display: none，dom都在

这的确是一个缺陷，我会尽快修复，在没有修复之前，你可以使用一个组件，然后调用 `navigateByUrl(url, { replaceUrl: true })` 代替 redirectTo

**Comment by sxhieen** [comment]
> > > 那你看看xxx是不是子应用的路由，有没有匹配到子应用
> > 
> > 
> > 应该是有匹配到的，因为一刷新就显示出来了，只是首次打开重定向的话，就display: none，dom都在
> 
> 这的确是一个缺陷，我会尽快修复，在没有修复之前，你可以使用一个组件，然后调用 `navigateByUrl(url, { replaceUrl: true })` 代替 redirectTo

谢谢~😊

**Comment by why520crazy** [comment]
please bump @worktile/planet to `1.1.3`
