### ISSUE TITLE
Multiples errors using on Angular 8

### ISSUE THREAD

**Issue by hernanBeiza** [worktile/ngx-planet#112]
Hi! First of all I want to say thanks you for your works! Looks great for spliting a huge modular app! I have questions about your library:

- I started using your library on Angular v8.3.28 and in the root app I had imported the NgxPlanetModule and I have this error: "An accessor cannot be declared in an ambient context."

![Screenshot from 2020-07-15 19-56-20](https://user-images.githubusercontent.com/1325005/87611535-50419e00-c6d6-11ea-8a62-0bfed84704c2.png)

- Is this library compatible with Angular 8? More details about my environment:
![Screenshot from 2020-07-15 20-03-12](https://user-images.githubusercontent.com/1325005/87611505-3dc76480-c6d6-11ea-8fcd-f5c5bf86eb46.png)

- Do you rercommend this library for a production environment?

**Comment by why520crazy** [comment]
1. You try setting "skipLibCheck": true in tsconfig.json to solved this problem, details see [an-accessor-cannot-be-declared-in-an](https://stackoverflow.com/questions/61248058/error-ngx-daterangepicker-material-an-accessor-cannot-be-declared-in-an-ambient)
```
"compilerOptions": {
    "skipLibCheck": true
}
```
2. ngx-planet is be dependent on `@angular/cdk`, you should run `npm i @angular/cdk --save` install @angular/cdk

Thank you for your feedback.

**Comment by hernanBeiza** [comment]
Hi @why520crazy  Now works like a charm! Now I can keep following the examples and keep working! Thanks for your reply!

**Comment by why520crazy** [comment]
> Hi @why520crazy Now works like a charm! Now I can keep following the examples and keep working! Thanks for your reply!
> PD: Both points could be added in Readme.md

good idea！
