### ISSUE TITLE
Angular 7 应该使用哪个版本？

### ISSUE THREAD

**Issue by zmpo** [worktile/ngx-planet#116]
ngx-planet  看上去是个不错的微前端库。
尝试过程中遇到这样的问题：

![angular7](https://user-images.githubusercontent.com/53931565/88875980-da504180-d254-11ea-905e-381ecfe1903e.PNG)

这似乎是依赖版本 不对，请问，可以用ngx-planet 的某个版本开发angular 7的应用吗

**Comment by zmpo** [comment]
还是用angular 9的一个应用先试试

**Comment by why520crazy** [comment]
你看下更新日志，具体报错行是什么，按理说是支持7.x的

**Comment by lvliang271486017** [comment]
> 还是用angular 9的一个应用先试试

支持angular8吗

**Comment by why520crazy** [comment]
ng8使用1.1.2版本
