### ISSUE TITLE
module 名称相同

### ISSUE THREAD

**Issue by lizhongkun** [worktile/ngx-planet#120]
app1 和 app2 项目下，都有一个UserModule，导致两个项目只请求一个UserModule（可能是缓存），这种情况怎么解决
![image](https://user-images.githubusercontent.com/41602501/89006168-ad755a80-d338-11ea-84ca-47619e6f8542.png)

**Comment by why520crazy** [comment]
因为每个子应用的路由前缀都不一样，请求的资源文件即是文件名一致也不会有问题的，可否具体描述一下

**Comment by lizhongkun** [comment]
app1和app2项目下有两个相同结构的userModule，我采用loadChildren的方式去加载这两个userModule，如果app1下的userModule先加载，再去点击路由加载app2下的userModule是就会报错
![image](https://user-images.githubusercontent.com/41602501/89241647-1eb35700-d632-11ea-91ea-a78df0630223.png)

**Comment by why520crazy** [comment]
那你确定懒加载的js路径是不是一样的？app1和app2需要配置不同的deployUrl

**Comment by why520crazy** [comment]
我有时间本地试试看

**Comment by ywager** [comment]
HI @why520crazy 同样遇到了这个问题 主应用和子应用有相同名称的module也会报上面的错

**Comment by why520crazy** [comment]
https://github.com/worktile/ngx-planet#faq

**Comment by why520crazy** [comment]
https://github.com/worktile/ngx-planet/blob/master/README.zh-CN.md#%E6%8A%A5%E9%94%99-cannot-read-property-call-of-undefined-at-__webpack_require__-bootstrap79

**Comment by why520crazy** [comment]
https://github.com/worktile/ngx-planet/blob/master/README.zh-CN.md#%E6%8A%A5%E9%94%99-cannot-read-property-call-of-undefined-at-__webpack_require__-bootstrap79

通过这里提供的方案试试。
