### ISSUE TITLE
The selector "**" did not match any elements

### ISSUE THREAD

**Issue by zmpo** [worktile/ngx-planet#121]
用 ng serve 运行时， 子应用报错，虽然**子应用内容显示正常**。
1. 注册应用
```

```
>  this.planet.registerApps([
>         {
>             name: 'weixin',
>             hostParent: '#app-host-container',
>             routerPathPrefix: '/weixin',
>             selector: 'weixin-root',
>             resourcePathPrefix: '/static/weixin/',
>             preload: false,
>             scripts: [
>                 'main.js'
>             ],
>         },
>     // start monitor route changes
>     // get apps to active by current path
>     // load static resources which contains javascript and css
>     // bootstrap angular sub app module and show it
>     this.planet.start();
>   }
```

```
2. 子应用main.ts 
```
defineApplication('weixin', (portalApp: PlanetPortalApplication) => {
    return platformBrowserDynamic([
        {
            provide: PlanetPortalApplication,
            useValue: portalApp
        }
    ])
        .bootstrapModule(AppModule)
        .then(appModule => {
            return appModule;
        })
        .catch(error => {
            console.error(error);
            return null;
        });
});
```
3. 子应用 AppModule
```
...
const routes: Routes = [
  {path: 'weixin', component: AppActualRootComponent},
]
...
bootstrap: [AppRootComponent],
...
```
4. 子应用 root.component.ts
```
....
@Component({
  selector: 'weixin-root-actual',
  templateUrl: './root.component.html',
  styleUrls: ['./root.component.css']
[})]([url](url))
export class AppActualRootComponent implements OnInit, OnDestroy {
...
@Component({
  selector: 'weixin-root', // tslint:disable-line
  template: '<router-outlet></router-outlet>'
})
export class AppRootComponent  {
}
...
```
5. 检查元素，有发现相应标签
![image](https://user-images.githubusercontent.com/53931565/89168458-7f4d8000-d5af-11ea-8167-ce8746b81f4b.png)

6. 报错的原因应该是说找不到 weixin-root 标签，报错具体代码如下
```
selectRootElement(selectorOrNode, preserveContent) {
        /** @type {?} */
        let el = typeof selectorOrNode === 'string' ? document.querySelector(selectorOrNode) :
            selectorOrNode;
        if (!el) {
            throw new Error(`The selector "${selectorOrNode}" did not match any elements`);
        }
        if (!preserveContent) {
            el.textContent = '';
        }
        return el;
    }
```

想知道怎么消除这个报错，请哪位大牛帮我看下，非常感谢 ^^

**Comment by zmpo** [comment]
特殊情况是，子应用的main.js 体积很大36.5MB。从现象上看，是先报的错，weixin-root-actual后渲染完成。
![apps](https://user-images.githubusercontent.com/53931565/89169275-9640a200-d5b0-11ea-8806-201f3bb1b951.gif)

**Comment by zmpo** [comment]
@why520crazy  能帮我看下吗？不知道我提供的信息够不够

**Comment by why520crazy** [comment]
可否提供一个在线示例，我不清楚是否会是其他问题导致的，正常情况会根据路由匹配到应用，然后生成root组件的selector元素，才会启动子应用，你打断点进去看看吧

**Comment by zmpo** [comment]
[demo.zip](https://github.com/worktile/ngx-planet/files/5019826/demo.zip)
这是一个demo，需要本地 `yarn install` 和 `npm run start`。不知道这种形式，方不方便你看问题。不行的话，我再想办法布置一个在线版。

**Comment by zmpo** [comment]
> 可否提供一个在线示例，我不清楚是否会是其他问题导致的，正常情况会根据路由匹配到应用，然后生成root组件的selector元素，才会启动子应用，你打断点进去看看吧

有时间帮看下

**Comment by zmpo** [comment]
main.ts 写错了， bootstrapModule(AppModule) 写了两遍
