### ISSUE TITLE
项目文件结构不能分开吗

### ISSUE THREAD

**Issue by norangit** [worktile/ngx-planet#122]
**Is your feature request related to a problem? Please describe.**
请问，作者您实际开发环境就跟github里面的目录结构一样的吗？多个子应用都是位于同一个项目里的不同文件夹，有没有可能主应用，子应用都是单独的项目结构呢？请问您是否在实际开发环境中，使用ngx-planet的同时，子应用是单独的项目的？

**Describe the solution you'd like**
我目前遇到的实际情况是，由于引用到了ng-alain，而ng-alain在使用ng add 命令添加的时候做了很多操作，导致默认的ng cli 生成的目录啊，配置啊有改动，如果是手工同步那些改动到主子应用同一个目录的话，有点复杂，且容易出错，不好维护，所以想每个应用还是保持单独的几乎标准的angular项目结构

**Comment by why520crazy** [comment]
这里的示例放一起方便理解和运行，这个是Demo，实际项目肯定是分仓储且独立的啊！

**Comment by norangit** [comment]
谢谢

**Comment by zxt888** [comment]
> **Is your feature request related to a problem? Please describe.**
> 请问，作者您实际开发环境就跟github里面的目录结构一样的吗？多个子应用都是位于同一个项目里的不同文件夹，有没有可能主应用，子应用都是单独的项目结构呢？请问您是否在实际开发环境中，使用ngx-planet的同时，子应用是单独的项目的？
> 
> **Describe the solution you'd like**
> 我目前遇到的实际情况是，由于引用到了ng-alain，而ng-alain在使用ng add 命令添加的时候做了很多操作，导致默认的ng cli 生成的目录啊，配置啊有改动，如果是手工同步那些改动到主子应用同一个目录的话，有点复杂，且容易出错，不好维护，所以想每个应用还是保持单独的几乎标准的angular项目结构

你好，我们现在项目也是用到ng-alain，方便可以提供一下ng-alain项目是如何配置的吗
