### ISSUE TITLE
可以支持子应用独立运行么？

### ISSUE THREAD

**Issue by stoning-code** [worktile/ngx-planet#130]

**Comment by walkerkay** [comment]
如果你想子应用独立启动的话， 我这边可以给提供一个思路，新建一个独立启动的main.ts，然后在 angular.json 中新增一个project的配置，利用angular启动时文件替换的功能来动态替换成你独立启动的main.ts，这样就跟一个普通的angular项目一样了 __

**Comment by stoning-code** [comment]
好的，非常感谢

> 如果你想子应用独立启动的话，我这边可以给提供一个思路，新建一个独立启动的main.ts，然后在angular.json中添加一个项目的配置，利用angular启动时文件替换的功能来动态替换成你独立启动的main.ts，这样就跟一个普通的angular项目一样了
> 
> ```
> // main.alone.ts
> 
> if (environment.production) {
>     enableProdMode();
> }
> 
> platformBrowserDynamic()
>     .bootstrapModule(BootstrapAloneModule)
>     .catch(err => console.error(err));
> ```
> 
> ```
> // angular.json 增加一个project配置
> 
>  "sky-alone": {
>       ... ,
>       "architect": {
>         "build": {
>             ...
>             // 主要是这块
>             "fileReplacements": [
>               {
>                 "replace": "src/main.ts",
>                 "with": "src/main.alone.ts"
>               }
>             ]
>           }
>         }
>       }
>     }
> ```
> 
> ```
> // package.json
> 
> {
>    scripts:{
>      "start-alone": "ng serve sky-alone"
>    }
> }
> ```

好的，非常感谢
