### ISSUE TITLE
子应用刷新后会出现加载错误信息

### ISSUE THREAD

**Issue by stoning-code** [worktile/ngx-planet#136]
@why520crazy @walkerkay 
当子应用路由激活状态下，刷新页面会抛异常，找不到当前应用，但是重新从主应用再进一次就好了。错误如图所示
![QQ截图20201113154520](https://user-images.githubusercontent.com/43668320/99042796-52eeca00-25c8-11eb-80b4-d9b7aabf666e.png)
package json如下
`
  "dependencies": {
    "@angular/animations": "~9.1.12",
    "@angular/cdk": "^9.2.4",
    "@angular/common": "~9.1.12",
    "@angular/compiler": "~9.1.12",
    "@angular/core": "~9.1.12",
    "@angular/forms": "~9.1.12",
    "@angular/platform-browser": "~9.1.12",
    "@angular/platform-browser-dynamic": "~9.1.12",
    "@angular/router": "~9.1.12",
    "ngx-sortablejs": "^3.1.4",
    "ngx-bootstrap": "5.2.0",
    "ngx-tethys": "8.1.0",
    "rxjs": "~6.5.5",
    "sortablejs": "1.8.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2",
    "bootstrap": "4.3.1",
    "ng-zorro-antd": "9.3.0"
  },
`

**Comment by why520crazy** [comment]
这个问题正在修复

**Comment by why520crazy** [comment]
通过错误看不出问题，可以提供更相信的信息或者示例吗

**Comment by why520crazy** [comment]
不知道有没有解决？看上去是使用了多个版本的rxjs导致的

**Comment by why520crazy** [comment]
先关闭了，有问题再提吧
