### ISSUE TITLE
你好，ngx-planet目前支持Angualr10吗？

### ISSUE THREAD

**Issue by hechanghong** [worktile/ngx-planet#144]
Would like to know that the angular 10+ can be supported or not, trying to evaluate the ng-planet stuff.
Can you please support to answer this question? I  found that anguarl@9 was used in the example, so want to check.
When I install CDk and got below warns, any ideas? thanks in advance!

- npm WARN @worktile/planet@1.2.4 requires a peer of @angular/common@^7.1.0 but none is installed. You must install peer dependencies yourself.
- npm WARN @worktile/planet@1.2.4 requires a peer of @angular/core@^7.1.0 but none is installed. You must install peer dependencies yourself.
- npm WARN @worktile/planet@1.2.4 requires a peer of @angular/cdk@^7.2.1 but none is installed. You must install peer dependencies yourself.
- npm WARN @worktile/planet@1.2.4 requires a peer of tslib@^1.10.0 but none is installed. You must install peer dependencies yourself.

Best Regards

**Comment by why520crazy** [comment]
You can ignore this warning，pure dependence is wrong，we will fix it.

**Comment by hechanghong** [comment]
> You can ignore this warning, pure dependences is wrong, we will fix it as soon as possible.

Thank you for your prompt reply. 
Good stuff, example is working well, pretty nice. 
and I am trying to split the example into multiple independent 3 repositories:portal, app1 and app2 to decouple the applications. 
I am struggling to make it work, but no luckies as of now. 
Does my idea make sence?  or it should not work at all? 
any advices will be highly appreciated. 
by the way, if any contribution required, i am more than happy to help.
