### ISSUE TITLE
IE浏览器里使用报错

### ISSUE THREAD

**Issue by liangGeek** [worktile/ngx-planet#168]
在IE11里面使用时，报“xxx's status is 3, can't be show or bootstrap”的错误，怎么解决啊？
angular9  node10  planet9
![报错图片](https://user-images.githubusercontent.com/48021297/105788215-00179280-5fbb-11eb-83a0-38daa00bcbc9.png)

![0009](https://user-images.githubusercontent.com/48021297/105787646-dc078180-5fb9-11eb-873b-80424a5af918.jpg)

**Comment by why520crazy** [comment]
Are other browsers throw the error？
Are there any other errors

**Comment by why520crazy** [comment]
#192 fixed, please upgrade to `11.0.0`
