### ISSUE TITLE
运行时，主程序能运行，子应用找不到manifest.json文件

### ISSUE THREAD

**Issue by wangjuanlsx** [worktile/ngx-planet#172]
![image](https://user-images.githubusercontent.com/18136723/108299519-88174380-71d9-11eb-8c88-6e29dde51ed4.png)
我的目录是这样的
![image](https://user-images.githubusercontent.com/18136723/108299607-b39a2e00-71d9-11eb-9186-6acfe4b3f87e.png)
angular.json的配置
![image](https://user-images.githubusercontent.com/18136723/108299989-6ff3f400-71da-11eb-802f-4b4e9966697f.png)
![image](https://user-images.githubusercontent.com/18136723/108299988-6ff3f400-71da-11eb-8347-fa016ff3ec5b.png)

**Comment by why520crazy** [comment]
you should start app1 with `ng serve app1 --deploy-url=/static/app1/`
