### ISSUE TITLE
运行ng serve app1 --deploy-url=/static/app1/ 报错

### ISSUE THREAD

**Issue by wangjuanlsx** [worktile/ngx-planet#173]
![image](https://user-images.githubusercontent.com/18136723/108479075-3dc4be00-72d0-11eb-9c08-4ae5972fd7b7.png)
package.json的依赖包
![image](https://user-images.githubusercontent.com/18136723/108479418-ac098080-72d0-11eb-8114-1a91d7a12df2.png)
这个报错是依赖包有需要固定版本吗

**Comment by why520crazy** [comment]
你自己看一下具体错误吧，angular-builders 改成10版本试试，angular cli 和 angular-builders 的版本不一致

**Comment by why520crazy** [comment]
示例是使用 ng 10 版本的，没有问题，你看一下区别吧
