### ISSUE TITLE
styles.scss没有转换成styles.css，转成了styles.js

### ISSUE THREAD

**Issue by wangjuanlsx** [worktile/ngx-planet#175]
![image](https://user-images.githubusercontent.com/18136723/108644062-5ad3d980-74e8-11eb-8aaf-171a6cfea726.png)
![image](https://user-images.githubusercontent.com/18136723/108644073-717a3080-74e8-11eb-8373-ab723145c3f5.png)
angular.json的配置
![image](https://user-images.githubusercontent.com/18136723/108644088-8951b480-74e8-11eb-9fe7-bd3dbd1f4d3d.png)
![image](https://user-images.githubusercontent.com/18136723/108644114-9b335780-74e8-11eb-853b-7ca1e1813c4e.png)
extra-webpack.config.js 配置
![image](https://user-images.githubusercontent.com/18136723/108644134-b8682600-74e8-11eb-910a-73eed0176f11.png)
![image](https://user-images.githubusercontent.com/18136723/108644141-c322bb00-74e8-11eb-9979-3036a10bf57e.png)
![image](https://user-images.githubusercontent.com/18136723/108644150-ccac2300-74e8-11eb-9a5b-be102306e5b1.png)

**Comment by wangjuanlsx** [comment]
原来跟extra-webpack.config,js无关，angular.json里少配置了"extractCss": true

**Comment by why520crazy** [comment]
> extractCss

。。。
