### ISSUE TITLE
多个子模块使用了懒加载，发布到nginx会报 Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by alanhuang1ok** [worktile/ngx-planet#178]
类似： https://github.com/worktile/ngx-planet/issues/120
1. 获取最新代码， 将 app1/src/app/user 代码复制到 app2 中
2. app2：  
          {
                path: 'users',
                loadChildren: () => import('./user/user.module').then(mod => mod.UserModule)
           },
此时运行项目：
npm run serve:portal // 3000
npm run serve:app1 // 3001
npm run serve:app2 // 3002
一切正常

但是假如执行 
build:portal:prod
build:app1:prod
build:app2:prod
配置到nginx上运行， 会报错 
Uncaught (in promise): TypeError: Cannot read property 'call' of undefined
TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (main.4c9b57731a432ae886b0.js:64) ....
先点app1的懒加载模块， 那么再点app2懒加载模块就会报错。    
先点app2的懒加载模块， 那么再点app1懒加载模块就会报错。
最新的代码已经配置"vendorChunk": false。

请问这问题怎么解决？

**Comment by wszgrcy** [comment]
你搜索下构建处理的3个项目的js文件,是不是会发现有两个或以上的项目中存在`webpackJsonp`这个?

**Comment by alanhuang1ok** [comment]
> 你搜索下构建处理的3个项目的js文件,是不是会发现有两个或以上的项目中存在`webpackJsonp`这个?

nginx 站点结构：
dist 
     |---portal
     |---static
                |---app1  (3.a7d310fe04f9c44eea53.js,main.f26e29ee8ecdb63ab96a.js 内容中都存在webpackJsonp)
                |---app2  (3.14b166f3cac63e4897cd.js,main.35427244abe0441334dd.js 内容中都存在webpackJsonp)

**Comment by wszgrcy** [comment]
> > 你搜索下构建处理的3个项目的js文件,是不是会发现有两个或以上的项目中存在`webpackJsonp`这个?
> 
> nginx 站点结构：
> 
> dist
> |---portal
> |-----------static/app1 (3.a7d310fe04f9c44eea53.js,main.f26e29ee8ecdb63ab96a.js 内容中都存在webpackJsonp)
> |-----------static/app2 (3.14b166f3cac63e4897cd.js,main.35427244abe0441334dd.js 内容中都存在webpackJsonp)

你可以通过手动配置`webpack`配置规避掉这个问题`config.output.jsonpFunction = 'examplesJsonp';`,`examplesJsonp`为个不相同的名字(x为你的子应用数量)
