### ISSUE TITLE
有支持v11的计划吗？

### ISSUE THREAD

**Issue by ycpaladin** [worktile/ngx-planet#187]
有支持v11的计划吗？

**Comment by why520crazy** [comment]
> 有支持v11的计划吗？

有

**Comment by ycpaladin** [comment]
> > 有支持v11的计划吗？
> 
> 有

有时间表不？我现在是ng 11, 要用这个，似乎还得降到10.

**Comment by why520crazy** [comment]
> > > 有支持v11的计划吗？
> 
> > 
> 
> > 有
> 
> 
> 
> 有时间表不？我现在是ng 11, 要用这个，似乎还得降到10.

应该是可以使用的，你看看有什么问题

**Comment by ycpaladin** [comment]
这个是浏览器控制台错误：
![image](https://user-images.githubusercontent.com/3337028/118763639-c260b180-b8aa-11eb-8186-01e770609e9d.png)

出现这个问题，似乎是主应用中的根组件执行了2次。

network中请求子应用中的 main.js 的状态是200
![image](https://user-images.githubusercontent.com/3337028/118763873-2aaf9300-b8ab-11eb-80d1-c949e649e333.png)
但是

**Comment by ycpaladin** [comment]
我找到问题了， 在angular.json 中 主应用的 "serve":"builder" 也应该是 "@angular-builders/custom-webpack:dev-server".
