### ISSUE TITLE
ng11 中的问题

### ISSUE THREAD

**Issue by ycpaladin** [worktile/ngx-planet#188]
1.第一次进入页面或者刷新页面，会出现 xxx 路由找不到的错误（开发环境和生产环境均有此问题）,但是功能模块能正确加载并显示出来，浏览器中的URL会重定向到根目录
![image](https://user-images.githubusercontent.com/3337028/118906329-2ee1bc00-b950-11eb-80c0-d9f5ae872a90.png)

![image](https://user-images.githubusercontent.com/3337028/118906672-cba45980-b950-11eb-9b87-52ca36a11513.png)

2.开发环境中切换功能，加载子路由模块的js文件的速度很慢，会超过10s
![image](https://user-images.githubusercontent.com/3337028/118906817-0c9c6e00-b951-11eb-81cc-fd77d0711f02.png)

相同的配置在ng10里面没有发现上述问题..

**Comment by ycpaladin** [comment]
找到原因了，主应用的路由里面要匹配 :
```typescript
{
    path: '**',
    component: EmptyComponent,
    children: [
      {
        path: '**',
        component: EmptyComponent,
        children: [
          {
            path: '**',
            component: EmptyComponent,
            children: [
              {
                path: '**',
                component: EmptyComponent,
                children: [
                  {
                    path: '**',
                    component: EmptyComponent,
                    children: [
                      {
                        path: '**',
                        component: EmptyComponent,
                        children: [

                        ]
                      },
                    ]
                  },
                ]
              },
            ]
          },
        ]
      },
    ]
  },
```

我的路由层级太多了。。

**Comment by ycpaladin** [comment]
这个有简化的办法吗？

**Comment by why520crazy** [comment]
> 生产环境中，从子应用之间跳转时出现以下错误：
> ![image](https://user-images.githubusercontent.com/3337028/118962909-7855f980-b998-11eb-8ee6-5520e18895f1.png)

Please make sure that the error is threw by planet？
see https://stackoverflow.com/questions/51485868/inject-must-be-called-from-an-injection-context

**Comment by ycpaladin** [comment]
> > 生产环境中，从子应用之间跳转时出现以下错误：
> > ![image](https://user-images.githubusercontent.com/3337028/118962909-7855f980-b998-11eb-8ee6-5520e18895f1.png)
> 
> Please make sure that the error is threw by planet？
> see https://stackoverflow.com/questions/51485868/inject-must-be-called-from-an-injection-context

看样子是ng的错误，第一次访问页面，和自应用内跳转没有问题，当切换到另一个自应用中时会出现这个错误。而且仅仅在生产环境中出现，开发模式不会。

您有什么建议吗？

**Comment by why520crazy** [comment]
http://planet.ngnice.com/  已经部署了最新的 ng 11，没有复现你说的问题，你可以测试一下，我发布了一个 `11.0.0` 你试试升级看看是否还有问题。

**Comment by ycpaladin** [comment]
我把项目里面的ng降到10了，也存在同样的问题. 一会儿再试试最新的版本

**Comment by why520crazy** [comment]
你测试一下 http://planet.ngnice.com/ 如果复现不了那就是你项目代码的问题

**Comment by ycpaladin** [comment]
> 你测试一下 http://planet.ngnice.com/ 如果复现不了那就是你项目代码的问题

 我的项目在拆分成微前端之前是一个ng应用，运行是没有任何问题的，上述问题是引入 planet 之后才出现的。
在引入planet之前我也尝试过 qiankun，对ng的支持也不是很好。

**Comment by why520crazy** [comment]
> > 你测试一下 http://planet.ngnice.com/ 如果复现不了那就是你项目代码的问题
> 
> 我的项目在拆分成微前端之前是一个完整的ng应用，里面大概有100+lazy module, 尽管在每次编译部署的时间超过8分钟，但是运行没有任何错误。上述问题是引入 planet 之后才出现的。
> 在引入planet之前我也尝试过 qiankun，对ng的支持也不是很好。

如果可以的话你提供一个可以复现的最小在线示例，我这边有时间可以排查一下，现在示例项目复现不了，不知道是你项目代码的问题还是结合在一起导致的，你可以断点定位一下问题，尝试设置 preserveSymlinks: true 试试，本地可以尝试配置  `optimization`, 
 `buildOptimizer` 和 `aot` 试试是优化掉了还是 aot 模式下的问题

**Comment by ycpaladin** [comment]
感谢您的建议. 我会尽快提供复现示例.

**Comment by ycpaladin** [comment]
仓库地址：https://github.com/ycpaladin/ng-micro-frontend-demo
在生产环境中切换自应用 URL 会出现错误。
感谢您能够在百忙中抽出时候帮我查找问题！

**Comment by why520crazy** [comment]
> 仓库地址：https://github.com/ycpaladin/ng-micro-frontend-demo
> 在生产环境中切换子应用 URL 会出现错误。
> 感谢您能够在百忙中抽出时候帮我查找问题！

我下载了你提供的示例，把所有的应用都加上 --prod 启动，发现【业务管理】下的路由切换都是正常的，只有【系统管理】切换会报错，而且报错的信息也不是这个 Issue 上说的那个，而是：
![image](https://user-images.githubusercontent.com/3959960/119286777-b6dd0400-bc77-11eb-9e0e-cc15494643ec.png)

你确定一下如何启动复现
![image](https://user-images.githubusercontent.com/3959960/119286864-e1c75800-bc77-11eb-9bbe-dcb9b33ed56a.png)

**Comment by ycpaladin** [comment]
抱歉， 让我再次澄清一下。
如您所见，
当（第一次）访问【业务管理】的时候，其下的子路由都访问正常。在切换到【系统管理】下的路由时，会出现错误。
反过来，
当（第一次）访问【系统管理】的时候，其下的子路由都访问正常，在切换到【业务管理】下的路由时，会出现相同的错误。

为什么没有出现我之前提供的错误信息，是因为我把原来组件内的代码都删除了，仅使用文本替代。

在我的项目中完整的错误信息如下：
![image](https://user-images.githubusercontent.com/3337028/119307054-a8094800-bc9d-11eb-9fa2-93c0abdec233.png)

1. 第一个错误正是我提供的仓库里面的代码中会出现的错误。
2. 第二个错误暂不讨论。
3. 第三个是才是我之前提供的错误。

我觉得第2、3个错误很可能与第1个错误有关联，换句话说就是如果解决了第1个错误，后面两个错误就不会出现了。

**Comment by why520crazy** [comment]
你这个是因为两个子应用都是用了懒加载， webpack 最终生成的 js 函数冲突导致的，参考：#178 使用自定义的 jsonpFunction 解决一下试试

**Comment by why520crazy** [comment]
给其中每个应用的 extra-webpack.config.js 加一个唯一的 jsonpFunction 即可
```
output: {
       jsonpFunction: "app2",
 },
```
