### ISSUE TITLE
Expected to not be in Angular Zone, but it is!

### ISSUE THREAD

**Issue by zChanges** [worktile/ngx-planet#197]
**Describe the bug**
Expected to not be in Angular Zone, but it is!
**To Reproduce**
The main app and sub-apps are both ng 12 version, planet 11 version
`planetComponentLoader.load` method of loading child components
It can be loaded normally, but an error will be reported. When the page is re-entered without refreshing, the sub-components cannot be displayed normally.
`planet` will fall back to 9.0.2, although there are errors, it can be loaded normally

**Screenshots**
![image](https://user-images.githubusercontent.com/16421725/122699496-1a108500-d27c-11eb-9cf0-b0b724d2513e.png)

**Comment by why520crazy** [comment]
do you try  uncomment the code `planet-application-ref.ts` ?

```
 NgZone.isInAngularZone = () => {
            // @ts-ignore
            return window.Zone.current._properties[`ngx-planet-${name}`] === true;
        };
```
In demo, we update to ng12, although the error is reported, it is running normally.

**Comment by why520crazy** [comment]
try upgrade planet to `12.0.0`

**Comment by zChanges** [comment]
Upgrade to the latest, no error is reported, after the first successful loading, it cannot be loaded without refreshing
@why520crazy
