### ISSUE TITLE
后续版本是否考虑增加样式隔离和JS沙箱相关功能呢？

### ISSUE THREAD

**Issue by solid12138** [worktile/ngx-planet#204]
目前项目中遇到了一些样式冲突和全局js冲突， 希望可以考虑后续增加相关功能， 谢谢

**Comment by why520crazy** [comment]
> 目前项目中遇到了一些样式冲突和全局js冲突， 希望可以考虑后续增加相关功能， 谢谢

样式隔离已经支持，看示例，JS沙箱隔离正在做

**Comment by why520crazy** [comment]
目前已经支持
