### ISSUE TITLE
请教使用问题

### ISSUE THREAD

**Issue by Eve-Sama** [worktile/ngx-planet#205]
我看了下demo里的案例代码, 有点小问题想请教一下. 在我的理解里, 主应用与子应用的路由是不可以重复的, 我看到demo里app1和app2是特意区分了路由的, ngx-planet是通过路由来匹配哪个项目对吗?

我本地有2个ng项目, 那么我想使用ngx-planet的话, 我起码得把2个项目都跑起来吧? 那Angular是不允许端口重复的,  那我就只能是一个localhost:4200/app1 另一个是locaohost:4201/app2  那我如果把app1当做主应用的话, 访问localhost:4200/app2, 那也匹配不上吧. 我不太理解ngx-planet对于多个项目多个端口是怎么处理的呢?

**Comment by why520crazy** [comment]
主应用使用了代理，当你访问 /static/app1 下静态资源的时候代理到子应用端口

**Comment by why520crazy** [comment]
至于/app1 /app2 都是访问主应用，主应用根据路由加载对用的应用，其实就是加载静态资源并启动子应用，渲染到指定区域。

**Comment by Eve-Sama** [comment]
那我的app1(主应用)在run的时候, 我也只是告诉了app1, 子应用是app2, 但是我都没告诉app1子应用的端口是4201, 那他的代理也不知道怎么代吧

**Comment by why520crazy** [comment]
主应用启动 devServer 的时候开启了代理，配置文件在：https://github.com/worktile/ngx-planet/blob/master/proxy.conf.js

需要在 `angular.json` 中配置代理：

```
 "serve": {
          "builder": "@angular-builders/custom-webpack:dev-server",
          "options": {
            "browserTarget": "portal:build",
            "proxyConfig": "proxy.conf.js",
            "port": 3000
          },
          "configurations": {
            "production": {
              "browserTarget": "portal:build:production"
            }
          }
        }
```
