### ISSUE TITLE
子应用热替换不生效

### ISSUE THREAD

**Issue by LstHeart** [worktile/ngx-planet#243]
**Describe the bug**

主应用和子应用同时运行时，子应用热替换无效

**To Reproduce**
1.本地环境，同时开启主应用和子应用，子应用添加--hmr开启热替换功能
2.修改子应用html内容后，浏览器未自动刷新修改的内容

**Expected behavior**
子应用开启热替换后，修改子应用html信息，浏览器能自动刷新显示最新内容

**Screenshots**

**Desktop:**
 - OS:  [win10]
 - Browser [chrome103.0.5060]
 - Version [ngx-planet13.0.0]

**Comment by why520crazy** [comment]
这个暂时不太好实现，子应用和主应用是独立的本地开发服务，建议本地开发采用独立启动的模式，需要把和主应用相关独立一个模块启动。

**Comment by LstHeart** [comment]
> 这个暂时不太好实现，子应用和主应用是独立的本地开发服务，建议本地开发采用独立启动的模式，需要把和主应用相关独立一个模块启动。

@why520crazy 如果独立启动的话，子应用可以获取主应用的数据吗？

**Comment by why520crazy** [comment]
> @why520crazy 如果独立启动的话，子应用可以获取主应用的数据吗？

独立启动需要你自己处理，把获取全局数据的服务放在独立启动的模块中

**Comment by why520crazy** [comment]
比如获取当前登录的用户，一般会在 Portal 中通过初始化服务获取，那么在独立启动的模块中，单独设置为初始化的服务。
我们这边通过定义一个`AloneModule`，在这个模块中注入全局的服务，配置全局的图标库等在 Portal 中初始化的数据，子应用独立启动时导入这个`AloneModule`

**Comment by LstHeart** [comment]
> 比如获取当前登录的用户，一般会在 Portal 中通过初始化服务获取，那么在独立启动的模块中，单独设置为初始化的服务。 我们这边通过定义一个`AloneModule`，在这个模块中注入全局的服务，配置全局的图标库等在 Portal 中初始化的数据，子应用独立启动时导入这个`AloneModule`

好的，谢谢！相当于是 主应用包含 `AloneModule`,子应用想要使用全局服务，也需要把 `AloneModule` 放到子应用里？

**Comment by why520crazy** [comment]
是的

**Comment by LstHeart** [comment]
了解了，谢谢！
