### ISSUE TITLE
routing mismatch when routerPathPrefix is similar with other sub application

### ISSUE THREAD

**Issue by Matcha-Toast** [worktile/ngx-planet#264]
**Describe the bug**
I got two application have similar name, one is 'app1' and the other is 'app1-similar'.
During the development, we only start  portal and app1-similar at local.
then enter browser, it try to load app1's manifest which I do not need.

**To Reproduce**
1. Using ngx-planet v12.1.0 example code (app2 as app1-similar)
2. change 'app2' routing path into 'app1-similar' in the app-routing,module.ts
![image](https://user-images.githubusercontent.com/89962815/207063161-595f2ad5-4496-41ed-92ad-811e19032861.png)

3. change app2 routerPathPrefix  into '/app1-similar' in the app.component.ts
![image](https://user-images.githubusercontent.com/89962815/207063264-17a3e090-af88-41f3-a1a5-4474daad3a59.png)
4. change  app2 routerLink into '/app1-similar'   
![image](https://user-images.githubusercontent.com/89962815/207063342-4a3f12b8-8217-41cd-8bb2-94a93207363b.png)
5. open browser and enter app2 
6. See error
![image](https://user-images.githubusercontent.com/89962815/207062860-20497a48-f350-4fa8-bad1-6b8fcfe17b95.png)

**Expected behavior**
Normal load sub application(app1-similar)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser : [Chrome]

**Comment by Matcha-Toast** [comment]
Hi 請問這項issue 有任何的建議 或更新嗎?  
謝謝

**Comment by why520crazy** [comment]
你可以把 app1-similar 和 app1 的定义顺序调换一下试试。

**Comment by why520crazy** [comment]
fixed in `18.0.1`
