### ISSUE TITLE
pingcode中登录模块是子应用吗？有子应用独立运行的例子吗？

### ISSUE THREAD

**Issue by youxinxie** [worktile/ngx-planet#266]
demo中没有登录的场景，登录一般是没有layout。而子应用是有layout的。跳转到登录页再回到主应用后，无法打开子应用（主要是跳转到登录页后，layout被销毁了，子应用渲染的容器也被销毁了）。遇到这个问题，不知道如何解决，烦请大佬抽空帮忙解答一下。是否可以提供一下pingcode登录模块的处理方法。

**Comment by why520crazy** [comment]
PingCode 的登录页是跳转的形式，不是一个子应用，不过你的场景我们也有，只要在子应用和登录应用之上加一个父路由组件即可，注册应用在父路由组件，所有子应用路由的父组件设置菜单和布局，你试试吧！

**Comment by youxinxie** [comment]
感谢大佬及时解答，我尝试着处理一下。
ngx-planet 13版本支持子应用独立运行吗？有子应用独立运行的例子吗？

**Comment by youxinxie** [comment]
大佬，您好。请教一个关于angular微前端拆分方面的问题：
我们项目组现在有两种拆分方案：
方案一： 子应用是完全独立的项目，各自使用独立依赖；共享模块使用npm包发布。
方案二：利用angular工作区多应用的概念：主子应用，公用库在同一个工作区，共享依赖。


此图为方案二的目录结构。
想请教一下大佬，这两种拆分方案哪种更好一些？拜谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "worktile/ngx-planet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月1日(星期三) 晚上6:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [worktile/ngx-planet] pingcode中登录模块是子应用吗？有子应用独立运行的例子吗？ (Issue #266)





 
Closed #266 as completed.

**Comment by why520crazy** [comment]
@youxinxie 各有利弊
方案1：每个子应用独立的团队负责，独立的 CI CD 流程，分开更合理，但是带来的问题是需要采用 npm 发共享模块，也就是业务组件库（我们采用的是此方案，需要做很多基建工作）
方案2：好处是开发快速，带来的问题是在一个仓储，多个团队维护起来可能有冲突


我建议人少项目初期的话采用方案2，项目可以快速推进，如果人多了以后分团队可能自然而然的会演变为方案1

**Comment by youxinxie** [comment]
非常感谢大佬的耐心解答，依据您的分析，我会认真思考最终采用的方案，再次感谢！！！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "worktile/ngx-planet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月10日(星期五) 上午8:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [worktile/ngx-planet] pingcode中登录模块是子应用吗？有子应用独立运行的例子吗？ (Issue #266)





 
@youxinxie 各有利弊
 方案1：每个子应用独立的团队负责，独立的 CI CD 流程，分开更合理，但是带来的问题是需要采用 npm 发共享模块，也就是业务组件库（我们采用的是此方案，需要做很多基建工作）
 方案2：好处是开发快速，带来的问题是在一个仓储，多个团队维护起来可能有冲突
 
我建议人少项目初期的话采用方案2，项目可以快速推进，如果人多了以后分团队可能自然而然的会演变为方案1
