### ISSUE TITLE
无限循环加载主应用的js

### ISSUE THREAD

**Issue by my5201314zwl** [worktile/ngx-planet#282]
**Describe the bug**
测试demo，使用ng serve 分别启动main-app和sub-app。
main-app能显示sub-app内容，但是无限循环加载主应用。
见附件

**To Reproduce**

**Expected behavior**

[micro-test.zip](https://github.com/worktile/ngx-planet/files/11419680/micro-test.zip)

**Comment by why520crazy** [comment]
1. sub-app "start" 改为 "ng serve --serve-path=/static/sub-app/",
2. main appregisterApps sub-app  注册子应用的时候设置 resourcePathPrefix 为 'http://localhost:3001/static/sub-app/'

Angular CLI 在某个版本的本地 Server 默认使用这个 serve-path 作为服务的地址，如果没有指定，主应用和子应用都是监听了同一个 Socket 服务，一直在 Reload 加载
