### ISSUE TITLE
在子应用中使用路由时，浏览器后退需要点多次才可后退

### ISSUE THREAD

**Issue by my5201314zwl** [worktile/ngx-planet#288]
**Describe the bug**
子项目中
const routes: Routes = [{
  path: '', component: HelloComponent,
  children: [
    {
      path: '', redirectTo: 'test1', pathMatch: 'full'
    },
    {
      path: 'test1', component: Test1Component
    },
    {
      path: 'test2', component: Test1Component
    }
  ]
}];

在test1和test2间进行路由切换，此时浏览器后退按钮不好用。

**To Reproduce**

**Expected behavior**

**Screenshots**
![1686272470367](https://github.com/worktile/ngx-planet/assets/6309339/fcc57d32-da8d-488e-9aae-6705e7d5b451)

**Desktop (please complete the following information):**
 - OS: window10
 - Browser:  chrome
 - Version: lastest

**Smartphone (please complete the following information):**

**Additional context**

**Comment by why520crazy** [comment]
微前端下使用 redirectTo 和 pathMatch: 'full' 有问题，
```
[
 {
   path: '', 
   redirectTo: 'test1', 
    pathMatch: 'full'
  },
]
```

升级到 15.1.1 版本，替换成 redirectToRoute 即可
```
[
 redirectToRoute('test1')
]
```
