### ISSUE TITLE
Assets from other apps

### ISSUE THREAD

**Issue by nikhiljj2018** [worktile/ngx-planet#50]
Hi how can we load the assets like images from other apps ?

**Comment by why520crazy** [comment]
Fist, you can define some rules for static resources
we put common assets at portal application, path rule is `/static/portal/assets/images/xxx.png` 
second, every app has a unique name, such as `app1` `apps`, their path is `/static/{{appName}}/assets/images/xxx.png`

so just access the path of the corresponding application's path, and prepend CDN base url prefix in production.

e.g.

`/static/portal/assets/images/xxx.png` 
`/static/app1/assets/images/xxx.png` 
`/static/app2/assets/images/xxx.png`

**Comment by why520crazy** [comment]
> Hi how can we load the assets like images from other apps ?
