### ISSUE TITLE
can't rerender when component is disposed in cross application rendering

### ISSUE THREAD

**Issue by why520crazy** [worktile/ngx-planet#51]
Open live demo
1. enter app1's dashboard, click Open App2's Project List, it will show project list
2. click Dispose App2's Project List, list will disposed
3. click again Open App2's Project List, it will throw error

**Comment by why520crazy** [comment]
please see https://juejin.im/post/5dddd9bb6fb9a0716a7db593#comment

**Comment by walkerkay** [comment]
https://github.com/worktile/ngx-planet/pull/72/commits/42cf56dadf83cd1897a772e564818df9667f41d7

This commit fix it
