### ISSUE TITLE
部署问题

### ISSUE THREAD

**Issue by oridark** [worktile/ngx-planet#52]
看了下portal和app1与app2都使用了package下的ngx-planet，那最后打包的时候，ngx-planet是单独打包单独部署吗，还是分别被打包到了三个应用中？

**Comment by why520crazy** [comment]
> 看了下portal和app1与app2都使用了package下的ngx-planet，那最后打包的时候，ngx-planet是单独打包单独部署吗，还是分别被打包到了三个应用中？

是的，目前  `ngx-planet` 的代码会被打包到三个应用中，因为 Angular 的 Lib 无法直接被运行时使用，等 Angular 9.0 发布后支持 Ivy 渲染引擎后，就可以做到 Angular Lib 公共依赖抽取。

目前只支持其他非 Angular 第三方库公共依赖抽取。

**Comment by oridark** [comment]
疑问已经解答清楚
