### ISSUE TITLE
当直接F5刷新应用1的路由，点击open App2 project list 按钮报错

### ISSUE THREAD

**Issue by yxxuweb** [worktile/ngx-planet#67]
当页面加载完毕，如果不用鼠标移入到app2的菜单，直接点击Open App2 Project list按钮，会报如下错误。虽然代码中定义了预加载2个应用，但是页面初始化完毕只加载了路由匹配的应用。

![image](https://user-images.githubusercontent.com/32837652/72198614-14015c80-346b-11ea-8dc8-e0be68898edd.png)

**Comment by why520crazy** [comment]
目前必须要应用2预加载完毕才可以调用，这个已经有一个issue需要修复。

**Comment by why520crazy** [comment]
#62
