### ISSUE TITLE
cannot load file from assets like /assets/images/*  /assets/js/*  /assets/*

### ISSUE THREAD

**Issue by shuihuasheng** [worktile/ngx-planet#69]
how to load file from assets like /assets/images/*  /assets/js/*  /assets/*

**Comment by why520crazy** [comment]
I don't fully understand, please describe it clearly.

`localhost:3000/assets/*` is redirect portal app.

if you access sub apps assets, please use `localhost:3000/static/app1/assets/*`, the `/static/app1` path is set in proxy.conf.js

**Comment by shuihuasheng** [comment]
sub app :  <img src="./assets/images/xxx.png" class="xxx-logo"> load-success
when i use "http://localhost:3000/static/app3/app3/login-system" load sub app  
the  <img src="./assets/images/xxx.png" class="xxx-logo"> redirectly to "http://localhost:3000/static/assets/images/soe.png" it is 404
sub app config   : "
ng serve -o --port=4400 --host=0.0.0.0  
--base-href=/static/app3/ 
--deploy-url=/static/app3/",

main app config: 
PROXY_CONFIG['/static/app3'] = {
    target: 'http://localhost:4400',
    secure: false,
    changeOrigin: true
};

            {
                name: 'app3',
                hostParent: '#app-host-container',
                selector: 'app3-root-container',
                // hostClass: appHostClass,
                routerPathPrefix: '/app3',
                scripts: [
                    '/static/app3/main.js',
                ],

            }

**Comment by shuihuasheng** [comment]
my solve is   <img [src..]="/static/app3/assets/images/xxx.png" class="xxx-logo">

it is not a Elegant solution;
