### ISSUE TITLE
请问单个应用部署时，如何访问应用下的路由？

### ISSUE THREAD

**Issue by zmzimpl** [worktile/ngx-planet#70]
例如我将app1编译打包放到容器中去了，这时候通过localhost:8080是能访问到这个应用的，但当我尝试访问localhost:8080/#/app1或者localhost:8080/#/app1/dashboard时，都不能加载对应的路由界面，是我没有正确访问，还是说本身并不支持?

**Comment by why520crazy** [comment]
采用微前端后，子应用是不可以直接访问的，子应用只提供静态资源文件，所有的路由都是访问 Portal，然后 Portal 会根据路由加载子应用的静态资源。

 比如示例中的 Portal 地址是：`localhost:3000`

当访问 `localhost:3000/app1` 会加载 App1 的 js 文件和样式文件渲染

**Comment by why520crazy** [comment]
如果是独立的应用，会在 js 加载完毕就渲染 Angular 应用，采用微前端后不是直接渲染的，而是主应用（Portal）出发渲染的。

**Comment by zmzimpl** [comment]
> 如果是独立的应用，会在 js 加载完毕就渲染 Angular 应用，采用微前端后不是直接渲染的，而是主应用（Portal）触发渲染的。

实际生产中会有将一个独立应用嵌入到其他应用中的情况，即既保证其能独立运行，又保证在少量改动之后能够作为微前端中的一个子应用存在。
想知道如果要将一个原本能够独立运行的应用嵌入到以ngx-planet搭建的微前端框架中，需要改动的地方大吗？都需要做哪些处理？

**Comment by why520crazy** [comment]
如果既需要独立运行又需要嵌入微前端，需要做多个入口以及适配调整，生成的 HTML 加载的是可以独立运行的脚本，提供一个单独的 main 入口给微前端使用

**Comment by myzhibie** [comment]
如果子应用无法独立访问，那么日常开发是如何去做的呢？

**Comment by why520crazy** [comment]
使用 Portal 访问啊，因为我们这边的子应用和主应用有数据交互和通信，独立访问不是说不可以，再写一个启动入口，让之前在 Portal 加载的数据在这个入口启动即可。

**Comment by why520crazy** [comment]
这个我之后在 Demo 中加一个独立访问的入口吧

**Comment by myzhibie** [comment]
> 这个我之后在 Demo 中加一个独立访问的入口吧

有没有线上生产环境的地址，去观摩一下

**Comment by why520crazy** [comment]
https://worktile.com/signup 注册一个企业，选择研发管理类型，进去就是采用 微前端 的产品

**Comment by zmzimpl** [comment]
> 这个我之后在 Demo 中加一个独立访问的入口吧

请问现在是否有支持单独访问的入口了？

**Comment by myzhibie** [comment]
> https://worktile.com/signup 注册一个企业，选择研发管理类型，进去就是采用 微前端 的产品

嗯，Chrome没问题，但是IE11还是会报错，worktile不支持IE11？
