### ISSUE TITLE
Error occurred while trying to proxy request 

### ISSUE THREAD

**Issue by HsienW** [worktile/ngx-planet#71]
Hi
I cloned project to the local end and run ng serve, without any modifications, but got this error

```
[HPM] Error occurred while trying to proxy request /static/app2/manifest.json?t=1582204653047 from localhost: 3000 to http: // localhost: 3002 (ECONNREFUSED) (https://nodejs.org/api/errors. html # errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /static/app2/manifest.json?t=1582204656987 from localhost: 3000 to http: // localhost: 3002 (ECONNREFUSED)
```

I am wondering how to solve this problem.

Thanks!

**Screenshots**

![image](https://user-images.githubusercontent.com/20525933/74948909-e92a0100-5437-11ea-97db-4c594b4f9222.png)

**My cli version**
![image](https://user-images.githubusercontent.com/20525933/74948990-0e1e7400-5438-11ea-948c-f983e17e8de2.png)

**Comment by why520crazy** [comment]
You need run npm start

**Comment by why520crazy** [comment]
npm run start will serve portal，app1 and app2，it's looks like you just started the portal.

**Comment by HsienW** [comment]
Oops! I mistook scripts, now everything works
thanks
