### ISSUE TITLE
子项目的模块是懒加载的，这些模块js 的 重定向怎么配置？

### ISSUE THREAD

**Issue by shuihuasheng** [worktile/ngx-planet#75]
子项目的模块是懒加载的，这些模块js 的 重定向怎么配置？

**Comment by why520crazy** [comment]
> 子项目的模块是懒加载的，这些模块js 的 重定向怎么配置？

Demo 中的有懒加载的示例，你看一下，子应用启动需要设置 `--deploy-url=/static/app2/`
![image](https://user-images.githubusercontent.com/3959960/75748809-476db280-5d5b-11ea-879b-e0bba1863992.png)

**Comment by why520crazy** [comment]
Close this issue.
