### ISSUE TITLE
Docs: add documentation on how to add sub apps

### ISSUE THREAD

**Issue by luxiaobei** [worktile/ngx-planet#84]

**Comment by SmallProgramIndustry** [comment]
@luxiaobei 您好兄弟，我看了上面的5410971文档，并且我有很多问题。 根据您的文档，它尚未实现。 如果您可以录制视频，只需创建一个子应用即可。

-------------------------------------------------------------------------------------

@luxiaobei  Hello brother, I looked at the 5410971 document above, and I have a lot of questions. According to your document, it has not been implemented. If you can record a video, simply create a sub-app.

**Comment by CodingYiyi** [comment]
I followed the doc above, and get an error 
" /manifest.json?t=1586504597779 404 (Not Found)"
I'm tired, really…
I 'm appreciate if someone can provide a fully-executable Demo.

**Comment by SmallProgramIndustry** [comment]
@CodingYiyi  部署的时候，虽然提示报错了，但是能完全运行。我本地运行，就没报错了。好蒙

**Comment by why520crazy** [comment]
子应用需要生成 manifest.json，然后保证注册的地址 manifest.json 可以正常访问到对一个子应用的

**Comment by luxiaobei** [comment]
> @luxiaobei 您好兄弟，我看了上面的5410971文档，并且我有很多问题。 根据您的文档，它尚未实现。 如果您可以录制视频，只需创建一个子应用即可。
> 
> @luxiaobei Hello brother, I looked at the [5410971](https://github.com/worktile/ngx-planet/commit/5410971f853dc81b44e7ec99fc1d4d094c7df437) document above, and I have a lot of questions. According to your document, it has not been implemented. If you can record a video, simply create a sub-app.

@SmallProgramIndustry you can refer to https://github.com/worktile/ngx-planet/pull/94
