### ISSUE TITLE
manifest.json 404 

### ISSUE THREAD

**Issue by SmallProgramIndustry** [worktile/ngx-planet#86]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
![image](https://user-images.githubusercontent.com/33216614/77150680-64321600-6acf-11ea-9ee8-192033f2177d.png)

**Comment by why520crazy** [comment]
We are writing a document about how to add an sub application such as app3.

You can check `proxy.conf`, should remove `pathRewrite` as app1 and app2

**Comment by CodingYiyi** [comment]
same error,
after checked the [proxy.conf] file,

**Comment by CodingYiyi** [comment]
is i  missing something？
