### ISSUE TITLE
cant serve application after run build

### ISSUE THREAD

**Issue by CodingYiyi** [worktile/ngx-planet#89]
**Describe the bug**
I can't serve this application after ran "npm run build", which listed in the [package.json] file

**To Reproduce**
1. npm run build
2. serve -s dist/    《== There is no response
although the below command can run a server successfully, but I can't reach app1 and app2 page
2.serve -s dist/planet

**Expected behavior**
how can i serve a application successfully with this framework

**Screenshots**
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/13033654/77813423-791c3400-70e3-11ea-8c7a-909e32bbda5b.png">

**Comment by why520crazy** [comment]
run `npm run start` to serve in local development.
