### ISSUE TITLE
子项目 css background-image 无效

### ISSUE THREAD

**Issue by CR903** [worktile/ngx-planet#91]
我是旧项目整合进来的，但是很多样式图片都失效了。

![image](https://user-images.githubusercontent.com/7643647/79530783-ed267800-80a2-11ea-9758-18bdcd717167.png)

但是图片失效了
![image](https://user-images.githubusercontent.com/7643647/79530871-3a0a4e80-80a3-11ea-9dfc-ca5f2794f30e.png)

应该如何配置？

**Comment by zhenshuaiwws** [comment]
#102 我在 Demo 中完善了一下，使用子应用的 assets 的示例，希望能帮助你

**Comment by zhenshuaiwws** [comment]
首先，明确一下 ngx-planet 的原理，如 Demo 中的结构，ngx-planet 底层实现其实会启动三个 angular 的 application，各自不同的端口，portal 端口为 3000，app1端口为3001。

请求子应用 app1 的资源文件通过在 angular.json 中设置 proxy.conf.js 代理，来加载 app1 的资源文件。


http://localhost:3000/static/app1/assets/github.png 代理到 http://localhost:3001/static/app1/assets/github.png

**Comment by zhenshuaiwws** [comment]
> 我是旧项目整合进来的，但是很多样式图片都失效了。
> 
> ![image](https://user-images.githubusercontent.com/7643647/79530783-ed267800-80a2-11ea-9758-18bdcd717167.png)
> 
> 但是图片失效了
> ![image](https://user-images.githubusercontent.com/7643647/79530871-3a0a4e80-80a3-11ea-9dfc-ca5f2794f30e.png)
> 
> 应该如何配置？
